spring.profiles.active: local

---

spring:
  profiles: local

spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/hr_leave_sys?useUnicode=true&characterEncoding=UTF-8
  username: root
  password: arms1234

spring.jpa:
  database: MYSQL
  show-sql: true
  hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

spring.thymeleaf:
  mode: LEGACYHTML5
  cache: false
  encoding: UTF-8

spring.mail:
  host: smtp.zoho.com
  username: benz.s@arms-thai.com
  password: benz1234
  port: 465
  properties.mail.smtp.auth: true
  properties.mail.smtp.ssl.enable: true

leave:
  jasper:
    path: src/main/resources/jasper

